=== 814ckf0x/BlackLynxFramework/src/etc/xml/xml-page.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Position related entities -->
<!ENTITY postop "0" >
<!ENTITY posleft "1" >
<!ENTITY posright "2" >
<!ENTITY posbuttom "3" >

<!-- Weight related entities -->
<!ENTITY ultralightweight "-1" >
<!ENTITY lightweight "0" >
<!ENTITY middleweight "2" >
<!ENTITY heavyweight "4" >
<!ENTITY ultraheavyweight "5" >

<!-- Element definitions -->
<!ELEMENT pagedocument (metadata?,messages?,blocks?,header?,contents?,footer?) >
<!ELEMENT metadata (title?,(meta|style|script)*) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT meta (charset?|(name?,value?)) >
<!ELEMENT charset (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT value (#PCDATA) >
<!ELEMENT style (media?,(type?,(src|code))) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT src (#PCDATA) >
<!ELEMENT code (#PCDATA) >
<!ELEMENT script ((async|defer|charset)*,type?,(src|code)) >
<!ELEMENT async EMPTY >
<!ELEMENT defer EMPTY >
<!ELEMENT messages (message*) >
<!ELEMENT message (type,title,msg_content) >
<!ELEMENT msg_content (#PCDATA) >
<!ELEMENT blocks (block*) >
<!ELEMENT block (position,weight,id?,title?,(content|nav_menu)) >
<!ELEMENT position (#PCDATA) >
<!ELEMENT weight (#PCDATA)>
<!ELEMENT id (#PCDATA) >
<!ELEMENT content (#PCDATA) >
<!ELEMENT nav_menu (nav_item+) >
<!ELEMENT nav_item (href,name,nav_item*) >
<!ELEMENT href (#PCDATA) >
<!ELEMENT header (legend,sub_legend?,nav_menu?) >
<!ELEMENT legend (#PCDATA) >
<!ELEMENT sub_legend (#PCDATA) >
<!ELEMENT contents (content_entry*) >
<!ELEMENT content_entry (weight,title?,content) >
<!ELEMENT footer (legend*,nav_menu?) >

=== 814ckf0x/BlackLynxFramework/doc/Examples/xml-page.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pagedocument SYSTEM "xml-page.dtd">
<!--
- This example page uses all available elements in the page object to give
- format to a text or adding objects like images you should use BBcode instead
- HTML. the page will automatically convert from BBcode to HTML.
-->
<pagedocument>
	<metadata>
		<title>xml DOM example</title>
		<meta>
			<charset>utf-8</charset>
		</meta>
		<meta>
			<name>application-name</name>
			<value>some application</value>
		</meta>
		<meta>
			<name>author</name>
			<value>814cf0x b14ckf0x at someser dot ver</value>
		</meta>
		<meta>
			<name>description</name>
			<value>A XML page example</value>
		</meta>
		<meta>
			<name>generator</name>
			<value>BlackLynxCMS</value>
		</meta>
		<meta>
			<name>keywords</name>
			<value>example,keywords,xml,document</value>
		</meta>
		<meta>
			<name>favicon</name>
			<value>path/to/icon.png</value>
		</meta>
		<style>
		  <media>somewhere</media>
			<type>text/css</type>
			<code>h1 {color:red;}</code>
		</style>
		<style>
			<type>text/css</type>
			<src>somewhere.js</src>
		</style>
		<script>
			<async/>
			<charset>utf-8</charset>
			<type>text/javascript</type>
			<code><![CDATA[ var i=20; ... ]]></code>
		</script>
		<script>
			<defer/>
			<src>some/path/to.js</src>
		</script>
	</metadata>
	<messages>
		<message>
			<type>modal_alert</type>
			<title>Unkown user</title>
			<msg_content>Not a valid user</msg_content>
		</message>
		<message>
			<type>modal_advertising</type>
			<title>advertising</title>
			<msg_content>Buy this thing</msg_content>
		</message>
		<!-- posible types: modal_alert, modal_advertising, modal_password,
		 - dorpdown_alert, dropdown_information, dropdown_debug
		-->
	</messages>
	<blocks>
		<block>
			<position>&postop;</position>
			<weight>&lightweight;</weight>
			<id>some_html_id</id>
			<title>leftblock</title>
			<content>hello world</content>
		</block>
		<block>
			<position>&posleft;</position>
			<weight>&middleweight;</weight>
			<id>main-navigation</id>
			<title>navigation-menu</title>
			<nav_menu>
				<nav_item>
					<href>http://to.somewhere.tld/main.php</href>
					<name>1.1 this is the anchor name or legend</name>
				</nav_item>
				<nav_item>
					<href>some/path/foo.php</href>
					<name>1.1 Go to foo</name>
					<nav_item>
						<href>some/path/foo.php?something=this</href>
						<name>1.1 Child pointing to this</name>
					</nav_item>
					<nav_item>
						<href>some/path/foo.php?something=bar</href>
						<name>1.1 other child</name>
					</nav_item>
				</nav_item>
			</nav_menu>
		</block>
	</blocks>
	<header><!-- header images are suposed to be set as backgrounds images with CSS -->
		<legend>BlackLynxFramework</legend>
		<sub_legend>Best framework ever</sub_legend>
		<nav_menu>
			<nav_item>
				<href>http://to.somewhere.tld/main.php</href>
				<name>this is the anchor name or legend</name>
			</nav_item>
			<nav_item>
				<href>some/path/foo.php</href>
				<name>Go to foo</name>
				<nav_item>
					<href>some/path/foo.php?something=this</href>
					<name>Child pointing to this</name>
				</nav_item>
				<nav_item>
					<href>some/path/foo.php?something=bar</href>
					<name>other child</name>
				</nav_item>
			</nav_item>
		</nav_menu>
	</header>
	<contents><!-- mandatory element -->
		<content_entry>
			<weight>1</weight>
			<title>some title</title>
			<content>some content here</content>
		</content_entry>
	</contents><!-- mandatory element -->
	<footer>
		<legend>This is the best page in the world, All rights reserver.</legend>
		<nav_menu>
			<nav_item>
				<href>some/path/about.php</href>
				<name>about</name>
			</nav_item>
			<!-- nav_item ... -->
		</nav_menu>
	</footer>
</pagedocument>
